default_stages: [commit]

repos:

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell --skip="*.js,*.html,*.css, *.svg" --ignore-words=.codespell-ignores.txt
        language: python
        types: [text]


  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=100
          - --max-cognitive-complexity=15
          - --ignore=E203,E266,E501,W503,F722
        additional_dependencies:
          - pep8-naming==0.13.3
          - flake8-absolute-import==1.0.0.1
          - flake8-bugbear==22.12.6
          - flake8-builtins==2.0.1
          - flake8-class-attributes-order==0.1.3
          - flake8-cognitive-complexity==0.1.0
          - flake8-comprehensions==3.10.1
          - flake8-pytest-style==1.6.0

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: debug-statements # Check for debugger imports
      - id: requirements-txt-fixer # Order requirements alphabetically
      - id: check-ast # Simply check whether the files parse as valid python
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-builtin-literals # Require literal syntax when initializing empty or zero Python builtin types
      - id: check-docstring-first # Check a common error of defining a docstring after code
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: check-yaml # Check yaml files
        args: ["--unsafe"]
      - id: end-of-file-fixer # Ensure that a file is either empty, or ends with one newline
      - id: mixed-line-ending # Replace or checks mixed line ending
      - id: trailing-whitespace # This hook trims trailing whitespace

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.1
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix, --ignore, F722,  --ignore, F841 ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
